---
version: '3.5'

services:
  send_mail:
    image: ykorzikowski/docker-send-attachments
    restart: on-failure
    environment:
    - INAME_FILTER=*.pdf
    - FROM_MAIL=from@mail
    - TARGET_MAIL=to@mail
    volumes:
    - ~/docker_volumes/send_mail/config/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    - ~/docker_volumes/send_mail/input:/input
    - ~/docker_volumes/send_mail/logs:/var/mail
